[package]
name = "aproxymate"
version = "0.1.0"
authors = ["Raven <sravendragon0@hotmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.9"
error-chain = "0.12"
printpdf = "0.2.8"

